export const RELAY_REGIONS = [
  {
    id: 1,
    region: 'Australia, New Zealand & South Pacific',
    hubs: 'Sydney Hub',
    city: 'Sydney, Australia',
    timezone: 'Australia/Sydney',
    utcOffset: 'UTC+10',
    code: 'OCN-01',
    lat: -33.8688,
    lng: 151.2093,
    question: 'CAN AI HELP US PROTECT THE LAND AND OCEANS WE SHARE?',
    producer: {
      name: 'Christina Gerakiteys',
      role: 'Regional Producer — Oceania & Pacific',
      bio: 'Christina unites marine ecologists, indigenous guardians, and AI researchers to explore regenerative intelligence across the Pacific and Oceania.',
      img: '/christina.jpg',
      tags: ['Regenerative AI', 'Ocean Health', 'Sydney Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 2,
    region: 'Japan, Korea, Taiwan & Northeast Asia',
    hubs: 'Kyoto Hub',
    city: 'Kyoto, Japan',
    timezone: 'Asia/Tokyo',
    utcOffset: 'UTC+9',
    code: 'JPN-02',
    lat: 35.0116,
    lng: 135.7681,
    question: 'WHEN MACHINES HELP CARE FOR US, WHAT ESSENCE OF LIFE & NATURE MUST WE PRESERVE?',
    producer: {
      name: 'Jun Sato',
      role: 'Regional Producer — Kyoto',
      bio: 'Jun anchors the Kyoto dialogue exploring how ancient Japanese concepts of Futokoro (懐) and Wa (和) inform compassionate autonomous systems, eldercare, and planet-centered coexistence.',
      img: '/jun.png',
      tags: ['Futokoro Philosophy', 'Compassionate Robotics', 'Kyoto Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 3,
    region: 'Southeast Asia',
    hubs: 'Youth Hub',
    city: 'Youth Hub / Southeast Asia',
    timezone: 'Asia/Singapore',
    utcOffset: 'UTC+8',
    code: 'SEA-03',
    lat: 1.3521,
    lng: 103.8198,
    question: 'CAN AI OPEN MORE DOORS FOR YOUTH WITHOUT LEAVING COMMUNITIES BEHIND?',
    producer: {
      name: 'Aditi Singh',
      role: 'Regional Producer — Southeast Asia / Youth Hub',
      bio: 'Aditi leads youth-empowered initiatives across Southeast Asia, fostering grassroots AI literacy, digital agency, and compassionate planet-centered technologies for the next generation.',
      img: '/aditi.jpg',
      tags: ['Youth Leadership', 'Digital Inclusion', 'Youth Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 4,
    region: 'South Asia',
    hubs: 'Thiruvananthapuram Hub',
    city: 'Thiruvananthapuram, India',
    timezone: 'Asia/Kolkata',
    utcOffset: 'UTC+5:30',
    code: 'IND-04',
    lat: 8.5241,
    lng: 76.9366,
    question: 'HOW CAN AI HELP MORE PEOPLE LEARN WITHOUT DISPLACING LIVING WISDOM?',
    producer: {
      name: 'Deepu S Nath',
      role: 'Regional Producer — South Asia',
      bio: 'Deepu leads grassroots technology and community education initiatives across South Asia, connecting youth ecosystems with compassionate, planet-centered AI architectures.',
      img: '/deepu.png',
      tags: ['Grassroots Tech', 'Youth Ecosystems', 'Kerala Hub'],
    },
    accent: '#C9A96A',
  },
  {
    id: 5,
    region: 'Middle East, Caucasus & Central Asia',
    hubs: 'Dubai Hub',
    city: 'Dubai, UAE',
    timezone: 'Asia/Dubai',
    utcOffset: 'UTC+4',
    code: 'GCC-05',
    lat: 25.2048,
    lng: 55.2708,
    question: 'WHEN CITIES BECOME SMARTER, WHO REMAINS RESPONSIBLE TO ALL LIVING SYSTEMS?',
    producer: {
      name: 'Walied Albasheer',
      role: 'Regional Producer — GCC & Middle East',
      bio: 'Walied leads the regional dialogue across the GCC and beyond on planet-centered AI governance, ethical deployment, and cross-continental innovation.',
      img: '/walied.jpg',
      tags: ['Civic AI Architecture', 'Cross-Continental Tech', 'Dubai Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 6,
    region: 'East Africa, Southern Africa & Central Europe',
    hubs: 'Nairobi & Berlin Hubs',
    city: 'Nairobi, Kenya',
    timezone: 'Africa/Nairobi',
    utcOffset: 'UTC+3',
    code: 'AFR-06',
    lat: -1.2921,
    lng: 36.8219,
    question: 'CAN AI BRING DECENTRALIZED CARE TO COMMUNITIES ACROSS THE BIOSPHERE?',
    producer: {
      name: 'Dr. Lee Kironget',
      role: 'Regional Producer — Africa',
      bio: 'Dr. Lee champions public health innovation, deploying localized diagnostic AI models and solar compute to frontline community clinics across East and Southern Africa.',
      img: '/lee.jpg',
      tags: ['Decentralized Health', 'African NLP', 'Nairobi Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 7,
    region: 'UK, Ireland, Iberia & West Africa',
    hubs: 'London Hub',
    city: 'London, UK',
    timezone: 'Europe/London',
    utcOffset: 'UTC+1',
    code: 'EUR-07',
    lat: 51.5074,
    lng: -0.1278,
    question: 'IF AI MAKES SYSTEMIC DECISIONS, HOW DO WE PRESERVE LIVING DIGNITY & CONTESTABILITY?',
    producer: {
      name: 'Fabrizio Gramuglio',
      role: 'Regional Producer — UK, Ireland, Iberia & West Africa',
      bio: 'Fabrizio leads European & West African initiatives uniting AI innovation, ecological sustainability, and ethical frameworks across the continent (Co-Producer: Edith Öller).',
      img: '/fabrizio.jpg',
      tags: ['European AI', 'Digital Ethics', 'London Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 8,
    region: 'Eastern & Southern South America, Caribbean',
    hubs: 'São Paulo Hub',
    city: 'São Paulo, Brazil',
    timezone: 'America/Sao_Paulo',
    utcOffset: 'UTC-3',
    code: 'LATAM-08',
    lat: -23.5505,
    lng: -46.6333,
    question: 'WHEN AI RESHAPES OUR COMMUNITIES, HOW DO WE CENTER INDIGENOUS WISDOM & NATURE?',
    producer: {
      name: 'Julieta Reyes',
      role: 'Regional Producer — Eastern & Southern South America, Caribbean',
      bio: 'Julieta convenes regional innovators and grassroots communities across South America and the Caribbean to bridge indigenous wisdom, environmental resilience, and compassionate AI systems.',
      img: '/julieta.jpg',
      tags: ['Indigenous Wisdom', 'Latin American AI', 'São Paulo Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 9,
    region: 'Eastern North America & Northern South America',
    hubs: 'New York Hub',
    city: 'New York, USA',
    timezone: 'America/New_York',
    utcOffset: 'UTC-4',
    code: 'NA-09',
    lat: 40.7128,
    lng: -74.006,
    question: 'WHEN AI CAN GENERATE SYNTHETIC REALITIES, HOW DO WE NURTURE LIVING TRUST?',
    producer: {
      name: 'Regional Anchor Community',
      role: 'Eastern North America & Northern South America',
      bio: 'Grassroots leaders and researchers across New York, Washington, Toronto, and Latin America addressing civil rights, democratic participation, and youth-led social movements.',
      img: '/city.png',
      tags: ['Civil Rights', 'Democratic AI', 'New York Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 10,
    region: 'Central North America & Mexico',
    hubs: 'Chicago & Mexico City Hubs',
    city: 'Mexico City, Mexico',
    timezone: 'America/Mexico_City',
    utcOffset: 'UTC-6',
    code: 'MEX-10',
    lat: 19.4326,
    lng: -99.1332,
    question: 'HOW CAN AI HONOR AND PRESERVE INDIGENOUS LANGUAGES AND LIVING TRADITIONS?',
    producer: {
      name: 'Stephen Butler & Nichol Bradford',
      role: 'Featured Regional Speakers — Central Americas',
      bio: 'Leading pioneers exploring transformative technology, cultural preservation, and linguistic diversity to bridge ancient oral heritage with modern machine learning.',
      img: '/butler.png',
      tags: ['Transformative Tech', 'Cultural Heritage', 'Mexico City Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 11,
    region: 'Western North America',
    hubs: 'Los Angeles Hub',
    city: 'Los Angeles, USA',
    timezone: 'America/Los_Angeles',
    utcOffset: 'UTC-7',
    code: 'USA-11',
    lat: 34.0522,
    lng: -118.2437,
    question: 'WHAT RESPONSIBILITY COMES WITH SCALING COMPUTE AT THE EDGE OF BIOSPHERE LIMITS?',
    producer: {
      name: 'Ani Chahal Honan',
      role: 'Regional Producer — Western North America',
      bio: 'Ani convenes media ethicists, creators, and technologists across Los Angeles, Silicon Valley, and the Pacific Rim exploring frontier AI, creativity, entertainment, and technology with compassion.',
      img: '/ani.jpg',
      tags: ['Frontier AI', 'Creativity & Media', 'Los Angeles Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 12,
    region: 'Hawaiʻi, Alaska & Pacific Islands',
    hubs: 'Honolulu Hub',
    city: 'Honolulu, Hawaii',
    timezone: 'Pacific/Honolulu',
    utcOffset: 'UTC-10',
    code: 'PAC-12',
    lat: 21.3069,
    lng: -157.8583,
    question: 'HOW DO WE EMBED INDIGENOUS OCEANIC STEWARDSHIP INTO PLANET-CENTERED AI?',
    producer: {
      name: 'Stephin Kalani',
      role: 'Featured Regional Speaker — Island & Oceanic Voices',
      bio: 'Stephin champions island sovereignty and indigenous data protocols, ensuring oceanic communities actively guide global AI governance and ecological curation.',
      img: '/stephin.webp',
      tags: ['Ocean Sovereignty', 'Community Stewardship', 'Honolulu Hub'],
    },
    accent: '#C9A96A',
  },
];
