export const RELAY_REGIONS = [
  {
    id: 1,
    region: 'Australia, New Zealand & South Pacific',
    hubs: 'Sydney Hub',
    city: 'Sydney, Australia',
    timezone: 'Australia/Sydney',
    utcOffset: 'UTC+11',
    code: 'OCN-01',
    lat: -33.8688,
    lng: 151.2093,
    question: 'CAN AI HELP US PROTECT THE LAND AND OCEANS WE SHARE?',
    producer: {
      name: 'Christina Gerakiteys',
      role: 'Regional Producer — Oceania & Pacific',
      bio: 'Christina unites marine ecologists, indigenous guardians, and AI researchers to explore regenerative intelligence across the Pacific and Oceania.',
      img: '/christina.jpg',
      tags: ['Regenerative AI', 'Ocean Health', 'Sydney Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 2,
    region: 'Japan, Korea, Taiwan & Northeast Asia',
    hubs: 'Kyoto, Osaka & Seoul Hubs',
    city: 'Kyoto & Osaka, Japan',
    timezone: 'Asia/Tokyo',
    utcOffset: 'UTC+9',
    code: 'JPN-02',
    lat: 35.0116,
    lng: 135.7681,
    question: 'WHEN MACHINES HELP CARE FOR US, WHAT SHOULD ALWAYS REMAIN HUMAN?',
    producer: {
      name: 'Jun Suto',
      role: 'Regional Producer — Kyoto & Osaka',
      bio: 'Jun anchors the dialogue exploring how ancient Japanese concepts of Futokoro (懐) and Ma (間) inform ethical autonomous systems and eldercare.',
      img: '/jun.png',
      tags: ['Futokoro Philosophy', 'Compassionate Robotics', 'Kyoto Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 3,
    region: 'Southeast Asia',
    hubs: 'Singapore & Jakarta Hubs',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    utcOffset: 'UTC+8',
    code: 'SEA-03',
    lat: 1.3521,
    lng: 103.8198,
    question: 'CAN AI OPEN MORE DOORS WITHOUT LEAVING PEOPLE BEHIND?',
    producer: {
      name: 'Mei-Ling Chen',
      role: 'Regional Producer — Southeast Asia',
      bio: 'Mei-Ling advocates for inclusive digital public infrastructure across ASEAN, ensuring multilingual AI literacy reaches rural and underserved communities.',
      img: '/alexis.png',
      tags: ['Digital Public Goods', 'Multilingual AI', 'Singapore Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 4,
    region: 'South Asia',
    hubs: 'Thiruvananthapuram & Bengaluru Hubs',
    city: 'Thiruvananthapuram, India',
    timezone: 'Asia/Kolkata',
    utcOffset: 'UTC+5:30',
    code: 'IND-04',
    lat: 8.5241,
    lng: 76.9366,
    question: 'HOW CAN AI HELP MORE PEOPLE LEARN WITHOUT REPLACING HUMAN JUDGMENT?',
    producer: {
      name: 'Kunal Sharma',
      role: 'Regional Producer — South Asia',
      bio: 'Kunal connects grassroots educators with open-source AI tutoring tools that augment human mentorship and community wisdom rather than replace it.',
      img: '/kunal.webp',
      tags: ['Grassroots Education', 'Open Weights', 'Kerala Hub'],
    },
    accent: '#C9A96A',
  },
  {
    id: 5,
    region: 'Middle East, Caucasus & Central Asia',
    hubs: 'Dubai & Riyadh Hubs',
    city: 'Dubai, UAE',
    timezone: 'Asia/Dubai',
    utcOffset: 'UTC+4',
    code: 'GCC-05',
    lat: 25.2048,
    lng: 55.2708,
    question: 'WHEN CITIES BECOME SMARTER, WHO REMAINS RESPONSIBLE?',
    producer: {
      name: 'Walied Albasheer',
      role: 'Regional Producer — GCC & Europe',
      bio: 'Walied leads the regional dialogue across the GCC and Europe on human-centered AI governance, ethical deployment, and cross-continental innovation.',
      img: '/walied.jpg',
      tags: ['Civic AI Architecture', 'Cross-Continental Tech', 'Dubai Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 6,
    region: 'East Africa, Southern Africa & Central Europe',
    hubs: 'Nairobi & Berlin Hubs',
    city: 'Nairobi, Kenya',
    timezone: 'Africa/Nairobi',
    utcOffset: 'UTC+3',
    code: 'AFR-06',
    lat: -1.2921,
    lng: 36.8219,
    question: 'CAN AI BRING EXPERTISE TO PEOPLE WHO DON’T HAVE ACCESS TO IT?',
    producer: {
      name: 'Dr. Lee Kironget',
      role: 'Regional Producer — Africa',
      bio: 'Dr. Lee champions public health innovation, deploying localized diagnostic AI models and solar compute to frontline community clinics across East and Southern Africa.',
      img: '/lee.jpg',
      tags: ['Decentralized Health', 'African NLP', 'Nairobi Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 7,
    region: 'UK, Ireland, Iberia & West Africa',
    hubs: 'London & Accra Hubs',
    city: 'London, UK',
    timezone: 'Europe/London',
    utcOffset: 'UTC+1',
    code: 'EUR-07',
    lat: 51.5074,
    lng: -0.1278,
    question: 'IF AI MAKES AN IMPORTANT DECISION, CAN A HUMAN QUESTION IT?',
    producer: {
      name: 'Ben Hawthorne',
      role: 'Regional Producer — UK & Atlantic',
      bio: 'Ben examines the ethics of algorithmic decision-making in public services, championing transparent legal recourse and explainable automated systems.',
      img: '/ben.webp',
      tags: ['Algorithmic Rights', 'Civic Oversight', 'London Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 8,
    region: 'Eastern & Southern South America',
    hubs: 'São Paulo & Buenos Aires Hubs',
    city: 'São Paulo, Brazil',
    timezone: 'America/Sao_Paulo',
    utcOffset: 'UTC-3',
    code: 'LATAM-08',
    lat: -23.5505,
    lng: -46.6333,
    question: 'WHEN AI CHANGES OUR WORK, WHO GETS A SAY?',
    producer: {
      name: 'Marques Anderson',
      role: 'Regional Producer — Latin America',
      bio: 'Marques creates bridges between indigenous wisdom keepers and emerging technology labs to build resilient, eco-positive socio-technical systems.',
      img: '/marques.jpg',
      tags: ['Indigenous Systems', 'Future of Work', 'São Paulo Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 9,
    region: 'Eastern North America & Northern South America',
    hubs: 'New York & Bogotá Hubs',
    city: 'New York, USA',
    timezone: 'America/New_York',
    utcOffset: 'UTC-4',
    code: 'NA-09',
    lat: 40.7128,
    lng: -74.006,
    question: 'WHEN AI CAN MAKE ANYTHING LOOK REAL, HOW DO WE KNOW WHAT TO TRUST?',
    producer: {
      name: 'Ani Chahal Honan',
      role: 'Regional Producer — North America',
      bio: 'Ani convenes media ethicists, provenance technologists, and educators to develop open standards for content authenticity and human-centric synthetic media.',
      img: '/ani.jpg',
      tags: ['Content Provenance', 'Digital Trust', 'New York Hub'],
    },
    accent: '#C96F4A',
  },
  {
    id: 10,
    region: 'Central North America & Mexico',
    hubs: 'Chicago & Mexico City Hubs',
    city: 'Mexico City, Mexico',
    timezone: 'America/Mexico_City',
    utcOffset: 'UTC-6',
    code: 'MEX-10',
    lat: 19.4326,
    lng: -99.1332,
    question: 'CAN AI UNDERSTAND EVERY LANGUAGE AND CULTURE?',
    producer: {
      name: 'Mateo Flores',
      role: 'Regional Producer — Central Americas',
      bio: 'Mateo works with indigenous linguists across Mexico and the Americas to train native language models that preserve cultural nuance and oral heritage.',
      img: '/flores.png',
      tags: ['Indigenous Language AI', 'Cultural Heritage', 'Mexico City Hub'],
    },
    accent: '#557C8B',
  },
  {
    id: 11,
    region: 'Western North America',
    hubs: 'Los Angeles & San Francisco Hubs',
    city: 'Los Angeles, USA',
    timezone: 'America/Los_Angeles',
    utcOffset: 'UTC-7',
    code: 'USA-11',
    lat: 34.0522,
    lng: -118.2437,
    question: 'WHAT RESPONSIBILITY COMES WITH BUILDING THE MOST POWERFUL AI?',
    producer: {
      name: 'Edith Vance',
      role: 'Regional Producer — Pacific Rim Tech',
      bio: 'Edith convenes frontier AI researchers, climate scientists, and ethicists to address the immense energy footprint and existential alignment challenges of frontier models.',
      img: '/edith.png',
      tags: ['Frontier Safety', 'Clean Compute', 'Silicon Valley Hub'],
    },
    accent: '#163B32',
  },
  {
    id: 12,
    region: 'Hawaiʻi, Alaska & Pacific Islands',
    hubs: 'Honolulu Hub',
    city: 'Honolulu, Hawaii',
    timezone: 'Pacific/Honolulu',
    utcOffset: 'UTC-10',
    code: 'PAC-12',
    lat: 21.3069,
    lng: -157.8583,
    question: 'HOW DO WE MAKE SURE SMALL COMMUNITIES ARE HEARD?',
    producer: {
      name: 'Stephin Kalani',
      role: 'Regional Producer — Island & Oceanic Voices',
      bio: 'Stephin champions island sovereignty and indigenous data protocols, ensuring oceanic communities actively guide global AI governance and ecological curation.',
      img: '/stephin.webp',
      tags: ['Ocean Sovereignty', 'Community Stewardship', 'Honolulu Hub'],
    },
    accent: '#C9A96A',
  },
];
