// 10 Public Planetary Segments for Global Relay Globe (with North America unified)
// Preserves underlying 12 operational blocks internally

export const RELAY_REGIONS = [
  {
    id: 1,
    segment: 'Oceania',
    region: 'Australia, New Zealand & South Pacific',
    shortName: 'Oceania',
    city: 'Oceania (Australia & Pacific)',
    timezone: 'Australia/Sydney',
    utcOffset: 'UTC+10',
    utcTiming: '07:00–09:00 UTC',
    code: 'OCN-01',
    lat: -33.8688,
    lng: 151.2093,
    theme: 'Indigenous wisdom, planetary stewardship and compassionate futures',
    blocks: [1],
    producer: {
      name: 'Christina Gerakiteys',
      role: 'Producer',
      segment: 'Oceania',
      bio: 'Christina Gerakiteys is CEO of UtopiaX, author, and global innovation strategist. She convenes marine ecologists, indigenous guardians, and AI researchers exploring regenerative intelligence across Oceania and the Pacific.',
      img: '/christina.jpg',
      tags: ['Moonshot Thinking', 'Ocean Health', 'Regenerative AI'],
      slug: 'christina-gerakiteys',
    },
    accent: '#163B32',
  },
  {
    id: 2,
    segment: 'East Asia',
    region: 'Japan, Korea, Taiwan & Northeast Asia',
    shortName: 'East Asia',
    city: 'East Asia (Kyoto / Tokyo / Seoul / Taipei)',
    timezone: 'Asia/Tokyo',
    utcOffset: 'UTC+9',
    utcTiming: '09:00–11:00 UTC',
    code: 'JPN-02',
    lat: 35.0116,
    lng: 135.7681,
    theme: 'Planet-centered AI, education, robotics and intergenerational responsibility',
    blocks: [2],
    producer: {
      name: 'Jun Suto',
      role: 'Producer',
      segment: 'East Asia',
      bio: 'Jun anchors the East Asia dialogue exploring how ancient Japanese concepts of Futokoro (懐) and Wa (和) inform compassionate autonomous systems, robotics, and intergenerational responsibility.',
      img: '/jun.png',
      tags: ['Futokoro Philosophy', 'Compassionate Robotics', 'East Asia'],
      slug: 'jun-suto',
    },
    accent: '#C96F4A',
  },
  {
    id: 3,
    segment: 'Youth',
    region: 'Southeast Asia',
    shortName: 'Youth',
    city: 'Southeast Asia (Youth Network)',
    timezone: 'Asia/Singapore',
    utcOffset: 'UTC+8',
    utcTiming: '11:00–13:00 UTC',
    code: 'SEA-03',
    lat: 1.3521,
    lng: 103.8198,
    theme: 'Youth & AI+Compassion — Digital Agency, Emerging Voices & Grassroots Action',
    blocks: [3],
    producer: {
      name: 'Aditi Singh',
      role: 'Producer',
      segment: 'Youth',
      bio: 'Aditi leads youth-empowered initiatives across Southeast Asia, fostering grassroots AI literacy, digital agency, and compassionate planet-centered technologies for the next generation.',
      img: '/aditi.jpg',
      tags: ['Youth Leadership', 'Digital Inclusion', 'Southeast Asia'],
      slug: 'aditi-singh',
    },
    accent: '#557C8B',
  },
  {
    id: 4,
    segment: 'South Asia',
    region: 'South Asia',
    shortName: 'South Asia',
    city: 'South Asia (India & Regional Network)',
    timezone: 'Asia/Kolkata',
    utcOffset: 'UTC+5:30',
    utcTiming: '13:00–15:00 UTC',
    code: 'IND-04',
    lat: 8.5241,
    lng: 76.9366,
    theme: 'AI for social impact, youth opportunity, health & responsible governance',
    blocks: [4],
    producer: {
      name: 'Deepu S Nath',
      role: 'Producer',
      segment: 'South Asia',
      bio: 'Deepu leads grassroots technology and community education initiatives across South Asia, connecting youth ecosystems with compassionate, planet-centered AI architectures.',
      img: '/deepu.png',
      tags: ['Grassroots Tech', 'Youth Ecosystems', 'South Asia'],
      slug: 'deepu-s-nath',
    },
    accent: '#C9A96A',
  },
  {
    id: 5,
    segment: 'GCC',
    region: 'Middle East, Caucasus & Central Asia',
    shortName: 'GCC',
    city: 'Middle East, GCC & Central Asia',
    timezone: 'Asia/Dubai',
    utcOffset: 'UTC+4',
    utcTiming: '15:00–17:00 UTC',
    code: 'GCC-05',
    lat: 25.2048,
    lng: 55.2708,
    theme: 'Long-horizon governance, coexistence, peacebuilding and future cities',
    blocks: [5],
    producer: {
      name: 'Walied Albasheer',
      role: 'Producer',
      segment: 'GCC',
      bio: 'Walied leads the regional dialogue across the GCC and beyond on planet-centered AI governance, coexistence, peacebuilding, and future cities.',
      img: '/walied.jpg',
      tags: ['Civic AI Architecture', 'Cross-Continental Tech', 'GCC'],
      slug: 'walied-albasheer',
    },
    accent: '#163B32',
  },
  {
    id: 6,
    segment: 'Africa',
    region: 'East Africa, Southern Africa & Central Europe',
    shortName: 'Africa',
    city: 'East & Southern Africa, Central Europe',
    timezone: 'Africa/Nairobi',
    utcOffset: 'UTC+3',
    utcTiming: '17:00–19:00 UTC',
    code: 'AFR-06',
    lat: -1.2921,
    lng: 36.8219,
    theme: 'Global justice, climate resilience, peace, democracy and ethical governance',
    blocks: [6],
    producer: {
      name: 'Dr. Lee Kironget',
      role: 'Producer',
      segment: 'Africa',
      bio: 'Dr. Lee champions public health innovation, deploying localized diagnostic AI models and planetary governance frameworks across East/Southern Africa and Central Europe (with Brainy providing regional support).',
      img: '/lee.jpg',
      tags: ['Decentralized Health', 'African NLP', 'Regional Support: Brainy'],
      slug: 'dr-lee-kironget',
    },
    accent: '#C96F4A',
  },
  {
    id: 7,
    segment: 'Europe',
    region: 'UK, Ireland, Iberia & West Africa',
    shortName: 'Europe',
    city: 'UK, Ireland, Iberia & West Africa',
    timezone: 'Europe/London',
    utcOffset: 'UTC+1',
    utcTiming: '19:00–21:00 UTC',
    code: 'EUR-07',
    lat: 51.5074,
    lng: -0.1278,
    theme: 'Compassionate leadership, responsible innovation, migration and global citizenship',
    blocks: [7],
    producer: {
      name: 'Fabrizio Gramuglio',
      role: 'Producer',
      segment: 'Europe',
      bio: 'Fabrizio leads European initiatives combining AI and human dignity, building and formalising the Compassion Economy with Co-Producer Dr. Edith Öller.',
      img: '/fabrizio.jpg',
      tags: ['Compassion Economy', 'Digital Ethics', 'Co-Producer: Dr. Edith Öller'],
      slug: 'fabrizio-gramuglio',
    },
    accent: '#557C8B',
  },
  {
    id: 8,
    segment: 'Caribbean & LATAM',
    region: 'Caribbean & South America',
    shortName: 'Caribbean & LATAM',
    city: 'Curacao',
    timezone: 'America/Curacao',
    utcOffset: 'UTC-4',
    utcTiming: '21:00–23:00 UTC',
    code: 'LAT-08',
    lat: 12.1696,
    lng: -68.9900,
    theme: 'Civil rights, democratic participation, global health and youth-led social movements',
    blocks: [8],
    producer: {
      name: 'Julieta Reyes',
      role: 'Regional Producer - Caribbean & South America',
      segment: 'Caribbean & LATAM',
      bio: 'Julieta intentionally amplifies voices across South America and the Caribbean to connect high-level policy with localized impact.',
      img: '/julieta.jpg',
      tags: ['Caribbean resilience', 'Latin American AI', 'Curacao Hub'],
      slug: 'julieta-reyes',
    },
    accent: '#163B32',
  },
  {
    id: 9,
    segment: 'North America',
    region: 'Eastern, Central & Western North America, Mexico',
    shortName: 'North America',
    city: 'North America (Pan-Regional Hubs)',
    timezone: 'America/New_York',
    utcOffset: 'UTC-4',
    utcTiming: '23:00–05:00 UTC (Blocks 9–11)',
    code: 'NAM-09',
    lat: 37.7749,
    lng: -122.4194,
    theme: 'Frontier AI, whole-person health, civil rights, cross-border enterprise and technology with compassion',
    blocks: [9, 10, 11],
    coverage: [
      'Eastern North America & Northern South America (Block 9)',
      'Central North America & Mexico (Block 10)',
      'Western North America & Pacific Rim (Block 11)',
    ],
    producer: {
      name: 'Ani Chahal Honan',
      role: 'North America Lead / Producer',
      segment: 'North America',
      bio: 'Ani Chahal Honan provides umbrella leadership across North America, uniting deep tech, frontier labs, cognitive AI, whole-person health, and technology with compassion.',
      img: '/ani.jpg',
      tags: ['North America Lead', 'Deep Tech', 'Regenerative AI'],
      slug: 'ani-chahal-honan',
    },
    accent: '#C96F4A',
  },
  {
    id: 10,
    segment: 'Pacific Islands / Ocean',
    region: 'Hawaiʻi, Alaska & Pacific Islands',
    shortName: 'Pacific Islands / Ocean',
    city: 'Pacific Islands, Hawaiʻi & Alaska',
    timezone: 'Pacific/Honolulu',
    utcOffset: 'UTC-10',
    utcTiming: '05:00–07:00 UTC',
    code: 'PAC-10',
    lat: 21.3069,
    lng: -157.8583,
    theme: 'Ocean consciousness, Indigenous navigation, ecological responsibility & island communities',
    blocks: [12],
    producer: {
      name: 'Jun Suto',
      role: 'Producer',
      segment: 'Pacific Islands / Ocean',
      bio: 'Jun convenes the Pacific Islands & Ocean dialogue championing island sovereignty, ocean consciousness, ecological responsibility, and indigenous navigation protocols.',
      img: '/jun.png',
      tags: ['Ocean Sovereignty', 'Island Stewardship', 'Indigenous Wisdom'],
      slug: 'jun-suto',
    },
    accent: '#C9A96A',
  },
];
