export const scheduleLeft = [
  { time: "", title: "", subtitle: "", items: ["Tamami Tono"] },
  { time: "", title: "", subtitle: "", items: ["Sister Jenna"] },
  { time: "", title: "", subtitle: "", items: ["Hiroshi Ishiguro & Edi Pyrek"] },
  { time: "", title: "", subtitle: "", items: ["Yoichi Ochiai"] },
  { time: "", title: "", subtitle: "", items: ["Kunal Sood"] },
];

export const scheduleRight = [
  { time: "", title: "", subtitle: "", items: ["Narumi Yoshikawa"] },
  { time: "", title: "", subtitle: "", items: ["Dr. Olaf Witkowski"] },
  { time: "", title: "", subtitle: "", items: ["Toshie Takahashi"] },
  { time: "", title: "", subtitle: "", items: ["Alex Cahana"] },
  { time: "", title: "", subtitle: "", items: ["Ben Weber"] },
  { time: "", title: "", subtitle: "", items: ["Ahmer Inam"] },
];

export const global = [
  {
    subtitle: "Block 0",
    title: "Kyoto Opening Ceremony",
    time: "06:00-07:00 UTC",
    items: [
      "Jun Suto (Producer)",
      "Dr. Olaf Witkowski",
      "Carl Sundberg",
    ],
  },
  {
    subtitle: "Block 1",
    title: "Australia, New Zealand & South Pacific",
    time: "07:00-09:00 UTC",
    items: [
      "Christina Gerakiteys (Producer)",
      "Marianne Power",
      "Rob Lee",
      "Ian Haycroft",
    ],
  },
  {
    subtitle: "Block 2",
    title: "Japan, Korea, Taiwan & Northeast Asia",
    time: "09:00-11:00 UTC",
    items: [
      "Jun Suto (Producer)",
      "Ishizu Tomohiro",
      "Junko Hosomi",
      "Christopher Currell",
      "Sami Seghers",
    ],
  },
  {
    subtitle: "Block 3",
    title: "Southeast Asia",
    time: "11:00-13:00 UTC",
    items: [
      "Aditi Singh (Producer)",
      "Hikari Kii",
      "Parv Sharma",
      "Soofiya S",
    ],
  },
  {
    subtitle: "Block 4",
    title: "South Asia",
    time: "13:00-15:00 UTC",
    items: [
      "Deepu S Nath (Producer)",
      "Sandhya Sitoula",
      "Nidhi Sudhan",
      "Mohammed Y Safirulla",
      "Dr. Suresh Namboothiri",
      "Sobhana Jaya Madhavan",
      "Seeram Sambasiva Rao",
      "Nandakishore Laya",
      "AFM Yusuf Haider",
      "Deepak Gupta",
      "Prof. Roshan G. Ragel",
      "Pervez Hoodbhoy",
      "Achuth Sankar",
      "Arun Surendran",
      "P J Narayan",
      "Jayashankar Prasad",
      "Arundhathi Krishna",
    ],
  },
  {
    subtitle: "Block 5",
    title: "Middle East, Caucasus & Central Asia",
    time: "15:00-17:00 UTC",
    items: [
      "Walied Albasheer (Producer)",
      "Priya M Nair",
      "Mohamed Ezzaldinn",
      "Aigerim Zhangozina",
      "Ruslan",
      "Omar Aloyoun",
    ],
  },
  {
    subtitle: "Block 6",
    title: "East Africa, Southern Africa & Central",
    time: "17:00-19:00 UTC",
    items: [
      "Dr. Lee Kironget (Producer)",
      "Brainy Swaibu (Producer)",
      "Marko Lesukat",
      "Evelyn Lusenaka",
      "Patrick McCullough",
      "Dr. Ken West",
    ],
  },
  {
    subtitle: "Block 7",
    title: "UK, Ireland, Iberia & West Africa",
    time: "19:00-21:00 UTC",
    items: [
      "Fabrizio Gramuglio (Producer)",
      "Dr. Edith Öller (Co-Producer)",
      "Emily Kate Genatowski",
      "Neil Nassar",
      "Valérie M. Saintot",
      "Julie Hellmann",
      "Paolo Cervari",
      "Anand Mahurkar",
      "Paola Cervari",
      "Massimo Camplone",
      "Mike Warwick",
    ],
  },
  {
    subtitle: "Block 8",
    title: "Eastern & Southern South America & Caribbean",
    time: "21:00-23:00 UTC",
    items: [
      "Julieta Reyes (Producer)",
      "Jeremy Erasmus",
      "Dr. Guido Rojer",
      "Mr. Satesh Sookhai",
      "Ugo Blanco",
      "Violette Ayala",
      "Valeria Soler",
    ],
  },
  {
    subtitle: "Block 9, 10, 11",
    title: "North America Segment",
    time: "23:00-01:00 UTC",
    items: [
      "Ani Chahal Honan (Producer)",
      "Kunal Sood",
      "Gary Bolles",
      "Dr. Natalie Petouhoff",
      "Josh Sikkema",
      "Marques Anderson",
    ],
  },
  {
    subtitle: "Block 12",
    title: "Hawaiʻi, Alaska & Pacific Islands",
    time: "05:00-07:00 UTC",
    items: [
      "Jun Suto (Producer)",
      "Joshua Castle",
      "Linzi Boyd",
      "Mitch Hammer",
      "Zoe Milligan",
    ],
  },
  {
    subtitle: "Block 13",
    title: "Kyoto Closing Ceremony",
    time: "07:00-08:00 UTC",
    items: [
      "Jun Suto (Producer)",
      "Fabrizio Gramuglio",
      "Dr. Edith Öller",
      "Julieta Reyes",
      "Aditi Singh",
      "Deepu S Nath",
      "Ani Chahal Honan",
      "Brainy Swaibu",
      "Dr. Lee Kironget",
      "Walied Albasheer",
      "Christina Gerakiteys",
      "Carl Sundberg",
    ],
  },
];

export const kyoto = [
  {
    subtitle: "",
    title: "East Asia / Kyoto",
    time: "09:00-11:00 UTC",
    items: [
      "Jun Suto (Producer)",
      "Ishizu Tomohiro",
      "Junko Hosomi",
      "Christopher Currell",
      "Dr. Olaf Witkowski",
    ],
  },
];

export const preEvent = [
  { title: "Lab A", items: ["Los Angeles (PDT): Sept 29, 8:00–9:00 PM", "Vienna (CEST): Sept 30, 5:00–6:00 AM", "Tokyo (JST): Sept 30, 12:00–1:00 PM"] },
  { title: "Lab B", items: ["Los Angeles (PDT): Sept 29, 12:00–1:00 AM", "Vienna (CEST): Sept 30, 9:00–10:00 AM", "Tokyo (JST): Sept 30, 4:00–5:00 PM"] },
];

export const locations = [
  { label: "UTC", key: "UTC", offset: 0 },
  { label: "San Francisco (PDT)", key: "PDT", offset: -7 },
  { label: "Kyoto (JST)", key: "JST", offset: 9 },
  { label: "Mumbai (IST)", key: "IST", offset: 5.5 },
  { label: "Abu Dhabi (GST)", key: "GST", offset: 4 },
  { label: "London (BST)", key: "BST", offset: 1 },
  { label: "New York (EDT)", key: "EDT", offset: -4 },
  { label: "Lagos (WAT)", key: "WAT", offset: 1 },
  { label: "Rio de Janeiro (BRT)", key: "BRT", offset: -3 },
  { label: "Sydney (AEST)", key: "AEST", offset: 10 },
];
